version: '3.8'

services:
  frontend:
    build:
      context: ./auth-frontend 
      dockerfile: Dockerfile
    ports:
      - "1122:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_backend
      MYSQL_USER: ayush
      MYSQL_PASSWORD: ayushpassword
    ports:
      - "3309:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d

volumes:
  mysql-init:
